### ISSUE TITLE
SHEEEEEEEEEEEEEEEEEEESH

### ISSUE THREAD

**Issue by Haider-Mirza** [devraza/kagayaki-emacs#1]
NICE THEME BOIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII.

**Comment by devraza** [comment]
Thank you very much for the informative feedback.

**Comment by Haider-Mirza** [comment]
But boi, you gotta sell dat ting cuz you like that very gut them brev very cool brev remind me of americ a dream brewv

**Comment by devraza** [comment]
> But boi, you gotta sell dat ting cuz you like that very gut them brev very cool brev remind me of americ a dream brewv

Cringe guy. I'm moving to self-hosted stuff anyways.
